from __future__ import annotations

import os
import tempfile
import uuid
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .usfm import strip_usfm


class ParatextNoteError(RuntimeError):
    pass


def _iso_note_date() -> str:
    # Paratext Notes 1.1 requires fractional seconds (5+) and an explicit UTC offset.
    return datetime.now(timezone.utc).isoformat(timespec='microseconds')


def _atomic_write_xml(path: Path, root: ET.Element) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    ET.indent(root, space='  ')
    tree = ET.ElementTree(root)
    fd, tmp = tempfile.mkstemp(prefix=path.name + '.', suffix='.tmp', dir=str(path.parent))
    os.close(fd)
    try:
        tree.write(tmp, encoding='utf-8', xml_declaration=True)
        # Parse exact bytes before replacement.
        ET.parse(tmp)
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def load_or_create_notes(path: Path) -> ET.Element:
    if path.exists():
        root = ET.parse(path).getroot()
        if root.tag != 'notes' or str(root.attrib.get('version', '')) != '1.1':
            raise ParatextNoteError(f'Existing Paratext notes file is not Notes 1.1: {path}')
        return root
    return ET.Element('notes', {'version': '1.1'})


def append_paratext_note(
    path: str | Path,
    *,
    book_id: str,
    chapter: str | int,
    verse: str | int,
    verse_text: str,
    comment_text: str,
    reviewer: str,
    selected_text: str = '',
    note_type: str = 'AI Bridge Review',
    ext_user: str = 'translationCore AI Bridge',
    thread_id: str | None = None,
    metadata: dict[str, Any] | None = None,
) -> tuple[Path, str]:
    """Append a Paratext Notes 1.1-compatible thread to a standalone XML file.

    This produces Notes-schema XML that can be exchanged/imported or posted through a Paratext
    integration. It deliberately does not write note markers into Scripture text.
    """
    p = Path(path)
    comment_text = str(comment_text or '').strip()
    if not comment_text:
        raise ParatextNoteError('Paratext note text may not be empty.')
    reviewer = str(reviewer or 'AI Bridge Reviewer').strip()
    plain = strip_usfm(str(verse_text or ''))
    chosen = str(selected_text or '').strip()
    start = plain.find(chosen) if chosen else 0
    if start < 0:
        start = 0
        chosen = ''
    before = plain[max(0, start - 40):start]
    after_start = start + len(chosen)
    after = plain[after_start:after_start + 40]
    tid = thread_id or f'aibridge-{uuid.uuid4()}'
    root = load_or_create_notes(p)
    thread = ET.SubElement(root, 'thread', {'id': tid, 'type': str(note_type or 'AI Bridge Review')})
    sel_attrs = {
        'verseRef': f'{str(book_id).upper()} {chapter}:{verse}',
        'startPos': str(start),
        'selectedText': chosen,
    }
    if before: sel_attrs['beforeContext'] = before
    if after: sel_attrs['afterContext'] = after
    ET.SubElement(thread, 'selection', sel_attrs)
    comment = ET.SubElement(thread, 'comment', {
        'user': reviewer,
        'date': _iso_note_date(),
        'extUser': str(ext_user or reviewer),
    })
    content = ET.SubElement(comment, 'content')
    # Keep plain human-readable content fully schema-compatible. Metadata is appended as text
    # instead of inventing XML elements not accepted by the Notes 1.1 schema.
    if metadata:
        context_bits = []
        for k in ('decision', 'tool', 'checkId', 'severity', 'model'):
            if metadata.get(k): context_bits.append(f'{k}={metadata[k]}')
        if context_bits:
            comment_text = f'{comment_text}\n\n[AI Bridge: {"; ".join(context_bits)}]'
    content.text = comment_text
    _atomic_write_xml(p, root)
    return p, tid


def validate_notes_11(path: str | Path) -> dict[str, Any]:
    """Lightweight structural validator for the subset generated by AI Bridge."""
    p = Path(path)
    root = ET.parse(p).getroot()
    if root.tag != 'notes' or root.attrib.get('version') != '1.1':
        raise ParatextNoteError('Expected <notes version="1.1">.')
    threads = list(root.findall('thread'))
    for t in threads:
        if not t.attrib.get('id'): raise ParatextNoteError('Thread id is required.')
        s = t.find('selection')
        if s is None: raise ParatextNoteError('Thread selection is required.')
        for a in ('verseRef', 'startPos', 'selectedText'):
            if a not in s.attrib: raise ParatextNoteError(f'Selection attribute {a} is required.')
        try: int(s.attrib['startPos'])
        except Exception as e: raise ParatextNoteError('startPos must be an integer.') from e
        comments = list(t.findall('comment'))
        if not comments: raise ParatextNoteError('At least one comment is required.')
        for c in comments:
            if 'user' not in c.attrib or 'date' not in c.attrib or c.find('content') is None:
                raise ParatextNoteError('Comment user/date/content are required.')
    return {'version': '1.1', 'threads': len(threads), 'path': str(p)}
